"""Ground-truth regression test: gap_detector's output must match the hand-
verified audit table from the 2026-07-17 research pass, repo by repo. This is
the closest thing this design has to a ground-truth test, since the table was
independently hand-verified, not generated by the code under test.
"""

from pathlib import Path

import pytest

from readme_agent.readme.gap_detector import REQUIRED_ELEMENTS, detect

FIXTURES_DIR = (
    Path(__file__).resolve().parents[1] / "fixtures" / "readmes" / "real_audit_2026-07-17"
)

# (license_mentioned, products_org_link, products_com_link, relationship_explained)
EXPECTED = {
    "3d-java": (True, True, True, True),
    "3d-python": (True, True, True, True),
    "cells-java": (True, False, False, False),
    "cells-typescript": (True, False, False, False),
    "pdf-java": (True, False, True, True),
    "pdf-go": (True, False, True, False),
    "barcode-python": (True, False, False, False),
    "email-python": (False, False, False, False),
    "slides-java": (True, False, False, False),
    "words-python": (True, False, False, False),
    "font-python": (True, False, False, False),
    "note-python": (True, False, True, True),
    "tex-python": (True, False, False, False),
    "page-python": (True, False, False, False),
}

DETECTED_LICENSE_BY_REPO = {key: "MIT" for key in EXPECTED}


@pytest.mark.parametrize("repo_key", sorted(EXPECTED))
def test_gap_report_matches_audit_table(repo_key):
    fixture_path = FIXTURES_DIR / f"{repo_key}.md"
    text = fixture_path.read_text(encoding="utf-8")

    report = detect(text, detected_license=DETECTED_LICENSE_BY_REPO[repo_key])

    expected_license, expected_org, expected_com, expected_relationship = EXPECTED[repo_key]
    assert report.license_mentioned == expected_license, f"{repo_key}: license_mentioned"
    assert report.products_org_link == expected_org, f"{repo_key}: products_org_link"
    assert report.products_com_link == expected_com, f"{repo_key}: products_com_link"
    assert report.relationship_explained == expected_relationship, (
        f"{repo_key}: relationship_explained"
    )


def test_3d_java_is_fully_compliant():
    text = (FIXTURES_DIR / "3d-java.md").read_text(encoding="utf-8")
    report = detect(text, detected_license="MIT")
    assert report.fully_compliant
    assert report.gaps == []


def test_cells_java_is_fully_a_blank_slate():
    text = (FIXTURES_DIR / "cells-java.md").read_text(encoding="utf-8")
    report = detect(text, detected_license="MIT")
    assert not report.fully_compliant
    assert set(report.gaps) == {"products_org_link", "products_com_link", "relationship_explained"}


def test_pdf_java_is_missing_exactly_the_org_link():
    text = (FIXTURES_DIR / "pdf-java.md").read_text(encoding="utf-8")
    report = detect(text, detected_license="MIT")
    assert report.gaps == ["products_org_link"]


def test_email_python_is_missing_everything_including_license():
    text = (FIXTURES_DIR / "email-python.md").read_text(encoding="utf-8")
    report = detect(text, detected_license="MIT")
    assert set(report.gaps) == set(REQUIRED_ELEMENTS)
    assert not report.license_mentioned
    assert not report.fully_compliant
