"""Focused persisted README composition-lineage and source-placement controls."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from readme_agent.facts.schema_v2 import ProductFactsV2
from readme_agent.golden_set.review_fixtures import REVIEW_ARCHETYPES, build_review_facts
from readme_agent.readme.claim_accountability import build_readme_claim_accountability_map
from readme_agent.readme.claim_map import build_readme_claim_map
from readme_agent.readme.composition_lineage import build_composition_ledger
from readme_agent.readme.composition_lineage_validation import composition_ledger_errors
from readme_agent.readme.composition_operation_origins import (
    legacy_operation_provenance,
    replay_operation_origins,
)
from readme_agent.readme.document_operations import build_operation
from readme_agent.readme.document_renderer import build_readme_document_candidate
from readme_agent.readme.document_validation import validate_readme_document_candidate

PROJECT_ROOT = Path(__file__).resolve().parents[2]
PROOF_PATH = (
    PROJECT_ROOT
    / "plans"
    / "investigations"
    / "evidence"
    / "level8-local-immutable-snapshot-and-facts-corrected-acquisition-2026-07-24"
    / "immutable-snapshot-and-product-facts-proof.json"
)


def _review_facts() -> ProductFactsV2:
    return ProductFactsV2.model_validate(build_review_facts(REVIEW_ARCHETYPES[2]))


def _document_facts(org_repo: str) -> tuple[ProductFactsV2, str]:
    proof = json.loads(PROOF_PATH.read_text(encoding="utf-8"))
    pilot = next(item for item in proof["current_pilots"] if item["org_repo"] == org_repo)
    return ProductFactsV2.model_validate(pilot["product_facts_v2"]), pilot["snapshot"][
        "source_revision"
    ]


def test_legacy_finalizer_persists_nonempty_provenance_and_recomputes_accountability() -> None:
    org_repo = "aspose-cells-foss/Aspose.Cells-FOSS-for-Java"
    facts, revision = _document_facts(org_repo)
    source = "# Cells\n\nLegacy source detail."
    candidate, plan = build_readme_document_candidate(
        org_repo, source, facts, base_revision=revision
    )
    expected = legacy_operation_provenance(
        replay_operation_origins(source.encode("utf-8"), plan.operations)
    )

    assert plan.operations
    assert expected
    lineage_only = [
        binding
        for binding in plan.candidate_content_provenance
        if binding.authority_scope == "lineage_only"
    ]
    factual = [
        binding
        for binding in plan.candidate_content_provenance
        if binding.authority_scope == "factual_or_configured"
    ]
    assert lineage_only == expected
    assert factual
    assert all(binding.fact_ids and not binding.configured_standard_ids for binding in factual)
    assert any(segment.authority == "unbound" for segment in plan.composition_ledger.segments)
    baseline_decision = validate_readme_document_candidate(source, candidate, plan, facts)
    assert baseline_decision.checks["composition_lineage"] is False
    assert any(
        "substantive generated bytes lack exact candidate authority" in error
        for error in baseline_decision.errors
    )
    assert all(
        binding.authority_scope == "lineage_only" and binding.lineage_operation_id is not None
        for binding in lineage_only
    )
    claim_map = build_readme_claim_map(
        plan,
        facts,
        source_text=source,
        candidate_text=candidate,
    )
    recomputed = build_readme_claim_accountability_map(
        org_repo=org_repo,
        source_text=source,
        candidate_text=candidate,
        facts=facts,
        generated_claim_map=claim_map,
        candidate_content_provenance=plan.candidate_content_provenance,
        source_claim_resolutions=plan.source_claim_resolutions,
    )
    assert plan.claim_accountability == recomputed

    omitted = plan.model_copy(update={"candidate_content_provenance": []})
    omitted_decision = validate_readme_document_candidate(source, candidate, omitted, facts)
    assert omitted_decision.checks["composition_lineage"] is False

    first, *remaining = plan.candidate_content_provenance
    renamed = first.model_copy(update={"provenance_id": "forged-factual.owner"})
    renamed_plan = plan.model_copy(update={"candidate_content_provenance": [renamed, *remaining]})
    renamed_claim_map = build_readme_claim_map(
        renamed_plan,
        facts,
        source_text=source,
        candidate_text=candidate,
    )
    renamed_accountability = build_readme_claim_accountability_map(
        org_repo=org_repo,
        source_text=source,
        candidate_text=candidate,
        facts=facts,
        generated_claim_map=renamed_claim_map,
        candidate_content_provenance=renamed_plan.candidate_content_provenance,
        source_claim_resolutions=renamed_plan.source_claim_resolutions,
    )
    assert renamed_accountability == plan.claim_accountability
    assert (
        validate_readme_document_candidate(source, candidate, renamed_plan, facts).checks[
            "composition_lineage"
        ]
        is False
    )

    scope_flip = first.model_copy(
        update={
            "authority_scope": "factual_or_configured",
            "lineage_operation_id": None,
        }
    )
    scope_flip_plan = plan.model_copy(
        update={"candidate_content_provenance": [scope_flip, *remaining]}
    )
    assert (
        validate_readme_document_candidate(source, candidate, scope_flip_plan, facts).checks[
            "composition_lineage"
        ]
        is False
    )

    mismatched_owner = first.model_copy(
        update={"lineage_operation_id": "readme.nonexistent-operation"}
    )
    mismatched_plan = plan.model_copy(
        update={"candidate_content_provenance": [mismatched_owner, *remaining]}
    )
    mismatched_decision = validate_readme_document_candidate(
        source, candidate, mismatched_plan, facts
    )
    assert mismatched_decision.checks["composition_lineage"] is False
    assert any(
        "differs from exact operation-origin replay" in error
        for error in mismatched_decision.errors
    )

    extra = first.model_copy(update={"provenance_id": "document-operation.extra.9999"})
    extra_plan = plan.model_copy(
        update={"candidate_content_provenance": [*plan.candidate_content_provenance, extra]}
    )
    assert (
        validate_readme_document_candidate(source, candidate, extra_plan, facts).checks[
            "composition_lineage"
        ]
        is False
    )


def test_lineage_only_projection_must_exactly_equal_maximal_replay_runs() -> None:
    source = "old"
    candidate = "## Navigation\n\n"
    operation = build_operation(
        operation_id="readme.real-operation",
        operation="replace",
        source=source.encode("utf-8"),
        start=0,
        end=len(source.encode("utf-8")),
        replacement=candidate,
        fact_ids=[],
        treatment="presentation_policy_correction",
        rationale="Exercise exact replay-derived lineage completeness.",
    )
    operations = [operation]
    exact = legacy_operation_provenance(
        replay_operation_origins(source.encode("utf-8"), operations)
    )
    ledger = build_composition_ledger(source, candidate, operations, exact)

    assert [item.model_dump(mode="python") for item in ledger.candidate_provenance] == [
        item.model_dump(mode="python") for item in exact
    ]
    assert composition_ledger_errors(ledger, source, candidate, operations, exact) == []
    assert all(not segment.fact_ids for segment in ledger.segments)
    assert all(not segment.provenance_ids for segment in ledger.segments)
    assert all(
        segment.configured_standard_ids == ["readme.composition.mechanical-markdown-v1"]
        for segment in ledger.segments
    )

    partial = exact[0].model_copy(update={"candidate_byte_end": 13})
    wrong_span = exact[0].model_copy(update={"candidate_byte_start": 1})
    fake_owner = exact[0].model_copy(update={"lineage_operation_id": "readme.fake-operation"})
    for tampered in ([partial], [wrong_span], [fake_owner]):
        with pytest.raises(
            ValueError,
            match="differs from exact operation-origin replay",
        ):
            build_composition_ledger(source, candidate, operations, tampered)
        errors = composition_ledger_errors(ledger, source, candidate, operations, tampered)
        assert any("differs from exact operation-origin replay" in error for error in errors)


def test_lineage_only_rejects_real_but_wrong_operation_owner() -> None:
    source = "ab"
    candidate = "XY"
    operations = [
        build_operation(
            operation_id="readme.real-left",
            operation="replace",
            source=source.encode("utf-8"),
            start=0,
            end=1,
            replacement="X",
            fact_ids=[],
            treatment="presentation_policy_correction",
            rationale="Own the left generated byte.",
        ),
        build_operation(
            operation_id="readme.real-right",
            operation="replace",
            source=source.encode("utf-8"),
            start=1,
            end=2,
            replacement="Y",
            fact_ids=[],
            treatment="presentation_policy_correction",
            rationale="Own the right generated byte.",
        ),
    ]
    exact = legacy_operation_provenance(
        replay_operation_origins(source.encode("utf-8"), operations)
    )
    wrong_real_owner = exact[0].model_copy(
        update={"lineage_operation_id": exact[1].lineage_operation_id}
    )

    with pytest.raises(ValueError, match="differs from exact operation-origin replay"):
        build_composition_ledger(
            source,
            candidate,
            operations,
            [wrong_real_owner, exact[1]],
        )
