"""Complete README document-plan, adoption, correction, and idempotency tests."""

from __future__ import annotations

import json
from pathlib import Path

from readme_agent.facts.schema_v2 import ProductFactsV2
from readme_agent.readme.document_plan import ReadmeDocumentPlanV1
from readme_agent.readme.document_renderer import build_readme_document_candidate
from readme_agent.readme.document_validation import (
    DocumentCandidateValidationV1,
    accepted_fact_is_represented,
    validate_readme_document_candidate,
)
from readme_agent.readme.markers import find_presentation_span

PROJECT_ROOT = Path(__file__).resolve().parents[2]
# Corrected 2026-07-24: repointed from level8-local-immutable-snapshot-and-facts-2026-07-24/,
# captured before the Maven resolver fix (search.maven.org never indexed the org.aspose group,
# so it falsely reported every Java pilot's package NOT_PUBLISHED). See
# plans/investigations/evidence/package-acquisition-ground-truth-2026-07-24/.
PROOF_PATH = (
    PROJECT_ROOT
    / "plans"
    / "investigations"
    / "evidence"
    / "level8-local-immutable-snapshot-and-facts-corrected-acquisition-2026-07-24"
    / "immutable-snapshot-and-product-facts-proof.json"
)


def _facts(org_repo: str) -> tuple[ProductFactsV2, str]:
    proof = json.loads(PROOF_PATH.read_text(encoding="utf-8"))
    pilot = next(item for item in proof["current_pilots"] if item["org_repo"] == org_repo)
    return (
        ProductFactsV2.model_validate(pilot["product_facts_v2"]),
        pilot["snapshot"]["source_revision"],
    )


def _assert_compatibility_claim_block(
    decision: DocumentCandidateValidationV1,
    plan: ReadmeDocumentPlanV1,
) -> None:
    """Require sound compatibility mechanics while verified approval remains closed."""

    assert decision.valid is False
    assert decision.checks["claim_accountability_complete"] is False
    assert decision.checks["claim_accountability_gaps_visible"] is True
    assert decision.checks["composition_lineage"] is False
    assert any(
        "substantive generated bytes lack exact candidate authority" in error
        for error in decision.errors
    )
    assert all(
        passed
        for name, passed in decision.checks.items()
        if name not in {"claim_accountability_complete", "composition_lineage", "header_visuals"}
    )
    assert plan.claim_accountability is not None
    blockers = sorted(
        record.claim_id
        for record in plan.claim_accountability.claims
        if not record.currently_accountable
    )
    expected = f"claim accountability has {len(blockers)} blocking claim(s): " + ", ".join(
        blockers[:10]
    )
    assert expected in decision.errors
    assert all(
        error == expected
        or "substantive generated bytes lack exact candidate authority" in error
        or error == "candidate_exact_mermaid failed"
        or error == "fact-backed README header or Mermaid diagram is absent"
        for error in decision.errors
    )


def _force_source_build_acquisition(facts: ProductFactsV2) -> ProductFactsV2:
    """Return a copy of ``facts`` with the acquisition fact forced to a genuinely-
    unpublished (source_build) outcome -- a synthetic override proving the renderer's
    fallback path still works for a package that really isn't published, independent of
    real current registry state (see ecosystems/foss_coordinate.py's own "when no FOSS
    package exists, source_build is the correct outcome" rule)."""
    acquisition = facts.selected_fact("installation.verified_acquisition")
    forced = acquisition.model_copy(
        update={
            "value": {
                "method": "source_build",
                "outcome": "SOURCE_BUILD_VERIFIED",
                "detail": "synthetic: forced unpublished for this test",
            }
        }
    )
    other_facts = [fact for fact in facts.facts if fact.fact_id != acquisition.fact_id]
    return facts.model_copy(update={"facts": [*other_facts, forced]})


def test_legacy_presentation_span_preserves_inner_bytes_without_final_newline():
    source = "# Product\n\nExact bytes"
    candidate = (
        f'<!-- readme-agent:presentation hash="sha256:{"a" * 64}" '
        f'schema="3" inner-bytes="{len(source.encode("utf-8"))}" -->\n'
        f"{source}\n<!-- readme-agent:presentation:end -->\n"
    )

    span = find_presentation_span(candidate)

    assert span is not None
    assert span.content.encode("utf-8") == source.encode("utf-8")
    assert span.content_bytes == source.encode("utf-8")


def test_missing_usage_section_gets_the_verified_minimal_example():
    org_repo = "aspose-cells-foss/Aspose.Cells-FOSS-for-Java"
    facts, revision = _facts(org_repo)
    source = "# Aspose.Cells FOSS for Java\n\nSpreadsheet library for Java developers.\n"

    candidate, plan = build_readme_document_candidate(
        org_repo, source, facts, base_revision=revision
    )
    decision = validate_readme_document_candidate(source, candidate, plan, facts)

    _assert_compatibility_claim_block(decision, plan)
    assert "## Quick Start" in candidate
    assert facts.selected_fact("example.minimal").value["code"].rstrip() in candidate
    assert any(
        operation.operation_id == "readme.example.add-verified-minimal"
        and facts.selected_fact("example.minimal").fact_id in operation.fact_ids
        for operation in plan.operations
    )
    assert any(
        operation.operation_id == "readme.installation.add-verified"
        and facts.selected_fact("installation.verified_acquisition").fact_id in operation.fact_ids
        for operation in plan.operations
    )


def test_overview_validation_uses_visitor_facing_audience_render_view():
    org_repo = "aspose-cells-foss/Aspose.Cells-FOSS-for-Java"
    facts, revision = _facts(org_repo)
    audience = facts.selected_fact("product.audience")
    rendered_audience = audience.model_copy(
        update={"value": ["Developers using net for spreadsheet processing"]}
    )
    facts = facts.model_copy(
        update={
            "facts": [
                rendered_audience if fact.fact_id == audience.fact_id else fact
                for fact in facts.facts
            ]
        }
    )
    source = "# Aspose.Cells FOSS\n"

    candidate, plan = build_readme_document_candidate(
        org_repo, source, facts, base_revision=revision
    )
    decision = validate_readme_document_candidate(source, candidate, plan, facts)

    assert "Developers using .NET for spreadsheet processing" in candidate
    _assert_compatibility_claim_block(decision, plan)
    assert decision.checks["verified_overview_present"] is True


def test_derived_problem_is_represented_by_its_accepted_supporting_diagram_fact() -> None:
    facts, _ = _facts("aspose-cells-foss/Aspose.Cells-FOSS-for-Java")
    problem = facts.selected_fact("product.problems_solved")
    capability = facts.selected_fact("product.capabilities")
    capability_text = (
        capability.value[0] if isinstance(capability.value, list) else capability.value
    )
    derived_problem = problem.model_copy(
        update={
            "value": [capability_text],
            "supporting_fact_ids": [capability.fact_id],
        }
    )

    assert accepted_fact_is_represented(
        derived_problem,
        "The derived phrase is intentionally not duplicated here.",
        {capability.fact_id},
    )
    assert not accepted_fact_is_represented(
        derived_problem,
        "The derived phrase is intentionally not duplicated here.",
        set(),
    )


def test_missing_limitations_section_gets_every_verified_limitation():
    org_repo = "aspose-cells-foss/Aspose.Cells-FOSS-for-Java"
    facts, revision = _facts(org_repo)
    limitations = facts.selected_fact("product.limitations")
    source = "# Aspose.Cells FOSS for Java\n\nSpreadsheet library for Java developers.\n"

    candidate, plan = build_readme_document_candidate(
        org_repo, source, facts, base_revision=revision
    )
    decision = validate_readme_document_candidate(source, candidate, plan, facts)

    _assert_compatibility_claim_block(decision, plan)
    assert "## Scope and Limitations" in candidate
    for limitation in limitations.value:
        assert limitation in candidate
    assert any(
        operation.operation_id == "readme.limitations.add-verified"
        and limitations.fact_id in operation.fact_ids
        for operation in plan.operations
    )


def test_simple_license_declaration_is_replaced_without_duplication_or_copyright() -> None:
    org_repo = "aspose-cells-foss/Aspose.Cells-FOSS-for-Java"
    facts, revision = _facts(org_repo)
    source = """# Aspose.Cells FOSS for Java

## License

Aspose.Cells FOSS for Java is licensed under the [MIT License](License/LICENSE.txt).

Copyright © 2026 Aspose Pty Ltd.
"""

    candidate, plan = build_readme_document_candidate(
        org_repo, source, facts, base_revision=revision
    )
    decision = validate_readme_document_candidate(source, candidate, plan, facts)

    _assert_compatibility_claim_block(decision, plan)
    assert candidate.count("[MIT License](License/LICENSE.txt)") == 1
    assert "It permits use, modification, distribution, and commercial use" in candidate
    assert "Copyright © 2026 Aspose Pty Ltd." not in candidate
    operation_ids = {operation.operation_id for operation in plan.operations}
    assert "readme.license.replace-declaration" in operation_ids
    assert any(item.startswith("readme.license.remove-copyright:") for item in operation_ids)


def test_existing_limitations_section_is_not_duplicated():
    org_repo = "aspose-cells-foss/Aspose.Cells-FOSS-for-Java"
    facts, revision = _facts(org_repo)
    limitations = facts.selected_fact("product.limitations")
    source = (
        "# Aspose.Cells FOSS for Java\n\n"
        "Spreadsheet library for Java developers.\n\n"
        "## Limitations\n\n"
        + "\n".join(f"- {limitation}" for limitation in limitations.value)
        + "\n"
    )

    candidate, plan = build_readme_document_candidate(
        org_repo, source, facts, base_revision=revision
    )
    decision = validate_readme_document_candidate(source, candidate, plan, facts)

    _assert_compatibility_claim_block(decision, plan)
    assert candidate.count("## Scope and Limitations") == 1
    assert "## Known Limitations" not in candidate
    assert all(
        operation.operation_id != "readme.limitations.add-verified" for operation in plan.operations
    )


def test_existing_partial_limitations_section_is_completed_without_replacement():
    org_repo = "aspose-cells-foss/Aspose.Cells-FOSS-for-Java"
    facts, revision = _facts(org_repo)
    limitations = facts.selected_fact("product.limitations")
    source = (
        "# Aspose.Cells FOSS for Java\n\n"
        "Spreadsheet library for Java developers.\n\n"
        "## Limitations\n\n"
        "- Existing maintainer-authored limitation that must remain.\n\n"
        "## Support\n\n"
        "Open an issue for help.\n"
    )

    candidate, plan = build_readme_document_candidate(
        org_repo, source, facts, base_revision=revision
    )
    decision = validate_readme_document_candidate(source, candidate, plan, facts)

    _assert_compatibility_claim_block(decision, plan)
    assert candidate.count("## Scope and Limitations") == 1
    assert candidate.count("## Repository-Verified Constraints") == 1
    assert "Existing maintainer-authored limitation that must remain." in candidate
    for limitation in limitations.value:
        assert limitation in candidate
    assert any(
        operation.operation_id == "readme.limitations.complete-verified"
        and limitations.fact_id in operation.fact_ids
        for operation in plan.operations
    )


def test_commercial_other_platforms_directory_is_removed_without_hiding_technical_content():
    org_repo = "aspose-cells-foss/Aspose.Cells-FOSS-for-Java"
    facts, revision = _facts(org_repo)
    source = """# Aspose.Cells FOSS for Java

Spreadsheet library for Java developers.

## 🌐 Other platforms (official Aspose.Cells)

For the full-featured Aspose product, see the official libraries:

- Aspose.Cells for .NET
  - Product: https://products.aspose.com/cells/net/
  - Documentation: https://docs.aspose.com/cells/net/

## Platform compatibility

This repository targets the Java runtime described by its build manifest.
"""

    candidate, plan = build_readme_document_candidate(
        org_repo, source, facts, base_revision=revision
    )

    assert "## Other Platforms" not in candidate
    assert "Aspose.Cells for .NET" not in candidate
    assert "## Platform Compatibility" in candidate
    assert "targets the Java runtime" in candidate
    operation = next(
        operation
        for operation in plan.operations
        if operation.operation_id.startswith("readme.presentation.remove-commercial-directory:")
    )
    assert operation.operation == "remove"
    assert operation.protected_content_treatment == "presentation_policy_correction"


def test_decorative_emojis_are_removed_without_changing_code_or_technical_symbols():
    org_repo = "aspose-cells-foss/Aspose.Cells-FOSS-for-Java"
    facts, revision = _facts(org_repo)
    source = """# 📦 Aspose.Cells FOSS for Java

## ✨ Features

- ✅ Reads workbook files
- Copyright © 2026

```text
print("✅ preserved in code")
```

Inline code remains exact: `value = "✅"`.
"""

    candidate, plan = build_readme_document_candidate(
        org_repo, source, facts, base_revision=revision
    )

    assert "# Aspose.Cells FOSS for Java" in candidate
    assert "## Key Capabilities" in candidate
    assert "[Key Capabilities](#key-capabilities)" in candidate
    assert "- Create, load, modify, and save workbooks and worksheets." in candidate
    assert "- Reads workbook files" not in candidate
    assert "Copyright © 2026" not in candidate
    assert 'print("✅ preserved in code")' in candidate
    assert '`value = "✅"`' in candidate
    assert any(
        operation.operation_id == "readme.journey.key-capabilities" for operation in plan.operations
    )


def test_single_unverified_usage_example_is_replaced_instead_of_duplicated():
    org_repo = "aspose-3d-foss/Aspose.3D-FOSS-for-Java"
    facts, revision = _facts(org_repo)
    example = facts.selected_fact("example.minimal")
    facts = facts.model_copy(
        update={
            "facts": [
                fact.model_copy(update={"verification_state": "verified"})
                if fact.fact_id == example.fact_id
                else fact
                for fact in facts.facts
            ]
        }
    )
    source = """# Aspose.3D FOSS for Java

## Usage

Introductory guidance remains.

```java
Scene scene = new Scene("testdata/input/cube.obj");
scene.save("output.stl");
```

Follow-on guidance remains.
"""

    candidate, plan = build_readme_document_candidate(
        org_repo, source, facts, base_revision=revision
    )
    decision = validate_readme_document_candidate(source, candidate, plan, facts)

    _assert_compatibility_claim_block(decision, plan)
    assert 'new Scene("testdata/input/cube.obj")' not in candidate
    assert facts.selected_fact("example.minimal").value["code"].rstrip() in candidate
    assert candidate.count("```java") == 1
    assert "Introductory guidance remains." in candidate
    assert "Follow-on guidance remains." in candidate
    replacement = next(
        operation
        for operation in plan.operations
        if operation.operation_id == "readme.example.replace-unverified-minimal"
    )
    assert replacement.operation == "replace"
    assert replacement.protected_content_treatment == "authoritative_fact_correction"
    assert facts.selected_fact("example.minimal").fact_id in replacement.fact_ids


def test_cells_keeps_verified_maven_install_and_adds_verified_example():
    """Corrected 2026-07-24: org.aspose:aspose-cells-foss IS published on Maven
    Central (the prior resolver queried the wrong endpoint) -- the renderer must
    KEEP a correct install claim, not strip it. See test_genuinely_unpublished_
    package_still_replaces_install_with_source_build below for the fallback path."""
    org_repo = "aspose-cells-foss/Aspose.Cells-FOSS-for-Java"
    facts, revision = _facts(org_repo)
    assert facts.selected_fact("installation.verified_acquisition").value["method"] == (
        "maven_central"
    )
    source = """# Aspose.Cells FOSS for Java

Spreadsheet library for Java developers.

## Installation

```xml
<dependency>
  <groupId>org.aspose</groupId>
  <artifactId>aspose-cells-foss</artifactId>
  <version>1.0.0</version>
</dependency>
```

## Quick Start

Existing guidance.

## Known Limits

Only XLSX is supported.
"""

    candidate, plan = build_readme_document_candidate(
        org_repo, source, facts, base_revision=revision
    )
    decision = validate_readme_document_candidate(source, candidate, plan, facts)

    _assert_compatibility_claim_block(decision, plan)
    assert "<artifactId>aspose-cells-foss</artifactId>" in candidate
    assert "<version>26.7.0</version>" in candidate
    assert "<version>1.0.0</version>" not in candidate
    assert "mvn clean install" not in candidate
    assert facts.selected_fact("example.minimal").value["code"].rstrip() in candidate
    assert not any(
        operation.operation_id == "readme.installation.verified-source-replacement"
        for operation in plan.operations
    )
    assert any(
        operation.operation_id.startswith("readme.installation.correct-coordinate-version:")
        and operation.replacement_text == "26.7.0"
        for operation in plan.operations
    )


def test_genuinely_unpublished_package_still_replaces_install_with_source_build():
    """The fallback path this session's fix preserves: a package that really
    is NOT published still gets its install claim corrected to source-build."""
    org_repo = "aspose-cells-foss/Aspose.Cells-FOSS-for-Java"
    facts, revision = _facts(org_repo)
    facts = _force_source_build_acquisition(facts)
    source = """# Aspose.Cells FOSS for Java

Spreadsheet library for Java developers.

## Installation

```xml
<dependency>
  <groupId>org.aspose</groupId>
  <artifactId>aspose-cells-foss</artifactId>
  <version>1.0.0</version>
</dependency>
```

## Quick Start

Existing guidance.
"""

    candidate, plan = build_readme_document_candidate(
        org_repo, source, facts, base_revision=revision
    )
    decision = validate_readme_document_candidate(source, candidate, plan, facts)

    _assert_compatibility_claim_block(decision, plan)
    assert "<artifactId>aspose-cells-foss</artifactId>" not in candidate
    assert "mvn clean install" in candidate
    assert any(
        operation.operation_id == "readme.installation.verified-source-insertion"
        and operation.protected_content_treatment == "additive"
        for operation in plan.operations
    )
    assert any(
        operation.operation_id.startswith("readme.installation.remove-false-package-claim")
        and operation.protected_content_treatment == "authoritative_fact_correction"
        for operation in plan.operations
    )


def test_pdf_keeps_verified_registry_badge_and_corrects_manifest_version():
    """Corrected 2026-07-24: org.aspose:aspose-pdf-foss IS published -- the
    Maven Central badge is a correct claim and must be kept. The manifest-
    version correction op is independent of acquisition method and unaffected."""
    org_repo = "aspose-pdf-foss/Aspose.PDF-FOSS-for-Java"
    facts, revision = _facts(org_repo)
    source = """# Aspose.PDF FOSS for Java

[![Maven Central](https://img.shields.io/maven-central/v/org.aspose/aspose-pdf.svg)](https://search.maven.org/artifact/org.aspose/aspose-pdf)

PDF processing for Java.

## Status

**Version 26.7** is current.

## Installation

```xml
<dependency>
  <groupId>org.aspose</groupId>
  <artifactId>aspose-pdf</artifactId>
</dependency>
```

## Quick Start

Existing guidance.
"""

    candidate, plan = build_readme_document_candidate(
        org_repo, source, facts, base_revision=revision
    )
    decision = validate_readme_document_candidate(source, candidate, plan, facts)

    _assert_compatibility_claim_block(decision, plan)
    assert "central.sonatype.com/artifact/org.aspose/aspose-pdf-foss" in candidate
    assert "Maven Central: org.aspose:aspose-pdf-foss" in candidate
    assert "**Version 26.6.0**" in candidate
    assert "**Version 26.7**" not in candidate


def test_promotional_callout_is_removed_but_relationship_section_preserved():
    """Uses cells-java facts (not 3D): this test is about the promotional-callout
    op, orthogonal to which pilot's facts are used, and cells' example.minimal is
    locally verified in this environment while 3D's needs a Java 21 toolchain this
    session's environment lacks (FACT-014, unrelated pre-existing gap)."""
    org_repo = "aspose-cells-foss/Aspose.Cells-FOSS-for-Java"
    facts, revision = _facts(org_repo)
    source = """# Aspose.Cells FOSS for Java

Open-source spreadsheet processing for Java.

> FOSS is on https://products.aspose.org/cells/java/ and commercial is on https://products.aspose.com/cells/java/.

## About

The FOSS edition is open source; the commercial edition has broader format support.

## Usage

Existing guidance.
"""

    candidate, plan = build_readme_document_candidate(
        org_repo, source, facts, base_revision=revision
    )
    decision = validate_readme_document_candidate(source, candidate, plan, facts)

    _assert_compatibility_claim_block(decision, plan)
    assert not any(line.startswith(">") for line in candidate.splitlines())
    assert "Aspose.Cells Enterprise Edition has broader format support" in candidate
    assert "commercial edition" not in candidate


def test_identical_candidate_rerender_has_no_document_operations():
    org_repo = "aspose-cells-foss/Aspose.Cells-FOSS-for-Java"
    facts, revision = _facts(org_repo)
    source = "# Cells\n\nJava spreadsheets.\n\n## Quick Start\n\nExisting guidance.\n"
    candidate, _ = build_readme_document_candidate(org_repo, source, facts, base_revision=revision)

    rerendered, rerun_plan = build_readme_document_candidate(
        org_repo, candidate, facts, base_revision=revision
    )

    assert rerendered == candidate
    assert rerun_plan.adoption.already_adopted is True
    assert rerun_plan.adoption.metadata_location == "durable_evidence"
    assert rerun_plan.operations == []


def test_tampered_candidate_fails_independent_reconstruction():
    org_repo = "aspose-cells-foss/Aspose.Cells-FOSS-for-Java"
    facts, revision = _facts(org_repo)
    source = "# Cells\n\nJava spreadsheets.\n\n## Quick Start\n\nExisting guidance.\n"
    candidate, plan = build_readme_document_candidate(
        org_repo, source, facts, base_revision=revision
    )

    decision = validate_readme_document_candidate(
        source,
        candidate.replace("Java spreadsheets.", "Unsupported claim."),
        plan,
        facts,
    )

    assert decision.valid is False
    assert decision.checks["candidate_hash_matches"] is False
    assert decision.checks["document_reconstruction"] is False
    assert decision.checks["composition_lineage"] is False
