"""Verified README core-section ordering and loss-bounded consolidation."""

from __future__ import annotations

import json
from pathlib import Path

from readme_agent.facts.schema_v2 import ProductFactsV2
from readme_agent.readme.document_plan import ReadmeDocumentPlanV1
from readme_agent.readme.document_renderer import build_readme_document_candidate
from readme_agent.readme.document_structure import parse_headings
from readme_agent.readme.document_validation import (
    DocumentCandidateValidationV1,
    validate_readme_document_candidate,
)

PROJECT_ROOT = Path(__file__).resolve().parents[2]
PROOF_PATH = (
    PROJECT_ROOT
    / "plans"
    / "investigations"
    / "evidence"
    / "level8-local-immutable-snapshot-and-facts-corrected-acquisition-2026-07-24"
    / "immutable-snapshot-and-product-facts-proof.json"
)


def _facts() -> tuple[ProductFactsV2, str]:
    proof = json.loads(PROOF_PATH.read_text(encoding="utf-8"))
    pilot = proof["current_pilots"][0]
    return (
        ProductFactsV2.model_validate(pilot["product_facts_v2"]),
        pilot["snapshot"]["source_revision"],
    )


def _assert_compatibility_claim_block(
    validation: DocumentCandidateValidationV1,
    plan: ReadmeDocumentPlanV1,
) -> None:
    assert validation.valid is False
    assert validation.checks["claim_accountability_complete"] is False
    assert validation.checks["claim_accountability_gaps_visible"] is True
    assert validation.checks["composition_lineage"] is False
    assert all(
        passed
        for name, passed in validation.checks.items()
        if name not in {"claim_accountability_complete", "composition_lineage", "aspose_checks"}
    )
    assert plan.composition_ledger is not None
    unbound_errors = [
        f"{segment.segment_id}: substantive generated bytes lack exact candidate authority"
        for segment in plan.composition_ledger.segments
        if segment.authority == "unbound"
    ]
    assert unbound_errors
    assert plan.claim_accountability is not None
    blockers = sorted(
        record.claim_id
        for record in plan.claim_accountability.claims
        if not record.currently_accountable
    )
    expected = f"claim accountability has {len(blockers)} blocking claim(s): " + ", ".join(
        blockers[:10]
    )
    assert validation.errors == [*unbound_errors, expected]


def test_why_and_feature_sections_become_one_open_fact_backed_section():
    facts, revision = _facts()
    source = """# Product

## Why Product

- Create workbooks
- Read workbooks

Maintainer explanation remains useful.

## Installation

Existing installation guidance.

## Currently Available Features

- Create spreadsheets
- Update cell values

## Quick start

Existing quick start.
"""

    candidate, plan = build_readme_document_candidate(
        facts.org_repo,
        source,
        facts,
        base_revision=revision,
    )
    validation = validate_readme_document_candidate(source, candidate, plan, facts)
    h2s = [heading.title for heading in parse_headings(candidate) if heading.level == 2]

    _assert_compatibility_claim_block(validation, plan)
    assert h2s[:5] == [
        "Navigation",
        "At a Glance",
        "Key Capabilities",
        "Installation",
        "Quick Start",
    ]
    assert "\n## Why Product\n" not in candidate
    assert "\n## Currently Available Features\n" not in candidate
    assert "- Create, load, modify, and save workbooks and worksheets." in candidate
    assert "- Read and write cell values and apply spreadsheet styles." in candidate
    assert "Create spreadsheets" not in candidate
    assert "Create workbooks" not in candidate
    assert "<details>" not in candidate
    assert "### Why Product" in candidate
    assert "Maintainer explanation remains useful." in candidate
    operation = next(
        operation
        for operation in plan.operations
        if operation.operation_id == "readme.journey.key-capabilities"
    )
    assert operation.fact_ids

    unchanged, unchanged_plan = build_readme_document_candidate(
        facts.org_repo,
        candidate,
        facts,
        base_revision=revision,
    )
    assert unchanged == candidate
    assert not any(
        operation.operation_id == "readme.journey.key-capabilities"
        for operation in unchanged_plan.operations
    )


def test_missing_source_capabilities_are_generated_from_accepted_facts():
    facts, revision = _facts()
    source = """# Product

## Installation

Existing installation guidance.

## Quick start

Existing quick start.
"""

    candidate, plan = build_readme_document_candidate(
        facts.org_repo,
        source,
        facts,
        base_revision=revision,
    )
    h2s = [heading.title for heading in parse_headings(candidate) if heading.level == 2]

    assert h2s[:5] == [
        "Navigation",
        "At a Glance",
        "Key Capabilities",
        "Installation",
        "Quick Start",
    ]
    operation = next(
        operation
        for operation in plan.operations
        if operation.operation_id == "readme.journey.key-capabilities"
    )
    assert operation.fact_ids
    assert "## Key Capabilities" in candidate


def test_pure_list_source_variants_cannot_hide_or_duplicate_core_capabilities():
    facts, revision = _facts()
    source = """# Product

## Why Product

- Unverified inherited capability wording

## Features

- Another inherited capability inventory

## Installation

Existing installation guidance.
"""

    candidate, plan = build_readme_document_candidate(
        facts.org_repo,
        source,
        facts,
        base_revision=revision,
    )
    validation = validate_readme_document_candidate(source, candidate, plan, facts)

    _assert_compatibility_claim_block(validation, plan)
    assert candidate.count("## Key Capabilities") == 1
    assert "<details>" not in candidate
    assert "Unverified inherited capability wording" not in candidate
    assert "Another inherited capability inventory" not in candidate
    assert "- Create, load, modify, and save workbooks and worksheets." in candidate
